spring.application.name=backend
server.port=9090

spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=${DB_URL:jdbc:mysql://127.0.0.1:3306/medical_wiki?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.database=${REDIS_DB:0}
spring.data.redis.password=${REDIS_PASSWORD}

# OSS
aliyun.oss.endpoint=${ALIYUN_OSS_ENDPOINT:oss-cn-shanghai.aliyuncs.com}
aliyun.oss.accessKeyId=${ALIYUN_OSS_ACCESS_KEY_ID}
aliyun.oss.accessKeySecret=${ALIYUN_OSS_ACCESS_KEY_SECRET}
aliyun.oss.bucketName=${ALIYUN_OSS_BUCKET_NAME}

#springdoc.api-docs.enabled=true
#springdoc.swagger-ui.enabled=true
knife4j.enable=true
knife4j.setting.language=zh_cn
knife4j.setting.enable-swagger-models=true
knife4j.setting.enable-document-manage=true
knife4j.setting.swagger-model-name=entity list
